language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install jsonschema
  - pip install coveralls
# command to run tests
script: nosetests  --with-coverage --cover-package=flask_inputs
after_success: coveralls
